### ISSUE TITLE
Bug: ChangeStream Handling crashes with `error converting after: proto:\ │ │ u00a0invalid type: primitive.DateTime`

### ISSUE THREAD

**Issue by jabouchleih** [conduitio-labs/conduit-connector-mongo#79]
### Bug description

Hi everyone,

when using this community plugin I directly encountered an issue.  
When a incoming MongoDB ChangeStream event is received, the following error occurs:

**UI ERROR LOG**
> node mongodb-s3:mongodb stopped with error: github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func2 /app/pkg/pipeline/lifecycle.go:577 - source stream was stopped unexpectedly: github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run /app/pkg/pipeline/stream/source.go:136 - error reading from source: github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run.func1 /app/pkg/pipeline/stream/source.go:87 - read stream error: error converting payload: error converting after: proto: invalid type: primitive.DateTime: github.com/conduitio/conduit/pkg/plugin/standalone/v1.unwrapGRPCError /app/pkg/plugin/standalone/v1/client.go:165

CONDUIT ERROR LOG:
>  2023-09-13T18:35:59+00:00 ERR node stopped error="node mongodb-s3:mongodb stopped with error: source stream was stopped unexpectedly: error reading from source: read stream error: error converting payload: error converting after: proto:\u00a │
│ 0invalid type: primitive.DateTime" component=pipeline.Service node_id=mongodb-s3:mongodb stack=[{"file":"/app/pkg/pipeline/lifecycle.go","func":"github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func2","line":577},{"file":"/ap │
│ p/pkg/pipeline/stream/source.go","func":"github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run","line":136},{"file":"/app/pkg/pipeline/stream/source.go","func":"github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run. │
│ func1","line":87},{"file":"/app/pkg/plugin/standalone/v1/client.go","func":"github.com/conduitio/conduit/pkg/plugin/standalone/v1.unwrapGRPCError","line":165}]                                                                                   │
│ 2023-09-13T18:35:59+00:00 INF destination connector plugin successfully torn down component=connector.Destination connector_id=mongodb-s3-dlq                                                                                                     │
│ 2023-09-13T18:35:59+00:00 INF destination connector plugin successfully torn down component=connector.Destination connector_id=mongodb-s3:s3                                                                                                      │
│ 2023-09-13T18:35:59+00:00 ERR pipeline stopped error="node mongodb-s3:mongodb stopped with error: source stream was stopped unexpectedly: error reading from source: read stream error: error converting payload: error converting after: proto:\ │
│ u00a0invalid type: primitive.DateTime" component=pipeline.Service pipeline_id=mongodb-s3 stack=[{"file":"/app/pkg/pipeline/lifecycle.go","func":"github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func2","line":577},{"file":"/ap │
│ p/pkg/pipeline/stream/source.go","func":"github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run","line":136},{"file":"/app/pkg/pipeline/stream/source.go","func":"github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceNode).Run. │
│ func1","line":87},{"file":"/app/pkg/plugin/standalone/v1/client.go","func":"github.com/conduitio/conduit/pkg/plugin/standalone/v1.unwrapGRPCError","line":165}]                                                                                   │
│ 2023-09-13T18:35:59+00:00 ERR node stopped error="node mongodb-s3:s3-acker stopped with error: context canceled" component=pipeline.Service node_id=mongodb-s3:s3-acker stack=[{"file":"/app/pkg/pipeline/lifecycle.go","func":"github.com/condui │
│ tio/conduit/pkg/pipeline.(*Service).runPipeline.func2","line":577}]

I guess this is related to the $date BSON object but cannot confirm it.
Below, you'll find a sample configuration and payload.

Thanks and best regards,

Janes

### Steps to reproduce

1. Environment: 
 * Kubernetes (EKS) cluster on latest version 1.27
 * Conduit v0.7.2 linux/amd6
 * MongoDB Connector (latest): v0.1.0
 * S3 Connector (latest): v0.5.0
 * MongoDB 6.0.9
3. With this simple pipeline configuration: 
<details>
  <summary>Click me</summary>

```
version: 1.0 # parser version, the only supported version for now is 1.0 [mandatory]

pipelines: # a map of pipelines IDs and their configurations.
  mongodb-s3: # pipeline ID, has to be unique.
    status: "stopped" # pipelines status at startup, either running or stopped. [mandatory]
    connectors: # a map of connectors IDs and their configurations.
      mongodb: # connector ID, has to be unique per pipeline.
        type: "source" # connector type, either "source" or "destination". [mandatory]
        plugin: "standalone:mongo@v0.1.0" # connector plugin. [mandatory]
        name: "mongodb" # connector name, if not specified, connector ID will be used as name. [optional]
        settings: # map of configurations keys and their values.
          uri: "mongodb+srv:/some-cluster.someid.mongodb.net/"
          db: "SAMPLE"
          collection: "sample"
          auth.username: "my-user"
          auth.password: "my-password"
          auth.db: "admin"
          auth.mechanism: "SCRAM-SHA-1"
          snapshot: false
      s3:
        type: "destination"
        plugin: "builtin:s3@v0.5.0"
        name: "s3"
        settings:
          aws.bucket: "my-conduit-target-sample-bucket"
          aws.region: "eu-central-1"
          aws.accessKeyId: "myaccesskey"
          aws.secretAccessKey: "mysecretkey"
          format: "json"
```
</details>

4. With the following sample document

<details>
  <summary>Click me</summary>

```
{
    "_id": "genericId",
    "metaInformation": {
        "lastUpdate": {
            "$date": {
                "$numberLong": "1694115709655"
            }
        },
        "versionNumber": {
            "$numberLong": "1"
        }
    },
    "orders": {
        "inprogress": [
            {
                "orderId": "123456",
                "saleDate": {
                    "$date": {
                        "$numberLong": "1624579200000"
                    }
                }
            }
        ]
    },
    "customerInfo": {
        "customerRegistrationDate": {
            "$date": {
                "$numberLong": "1589760000000"
            }
        },
        "customerLoginDate": {
            "$date": {
                "$numberLong": "1575849600000"
            }
        }
    },
    "dateInfo": {
        "endDate": {
            "$date": {
                "$numberLong": "1589155200000"
            }
        },
        "plannedEndDate": {
            "$date": {
                "$numberLong": "1588896000000"
            }
        }
    },
    "schemaVersion": {
        "$numberDouble": "0.0"
    }
}
```
</details>

### Version

 Conduit v0.7.2 / MongoDB Connector v0.1.0
